#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: e2e_kind
on:
  push:
    branches: [ e2e_kind ]

jobs:
  pull-kubernetes-e2e-kind:
    name: pull-kubernetes-e2e-kind
    runs-on: ${{ matrix.runasos }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        runasos:
        # - ubuntu-22.04
        # - ubuntu-24.04
        - ubuntu-latest
        parallel:
        - true
        - false
        focus:
        - \[sig-storage\]
        # - should store data
        - "."
        # - \[sig-network\]
        branch: 
        - master 
        - 47c92e2ab7ad9076e11772ee130b82dc2cfa1add
        # - release-1.30
        # - release-1.29
        # - release-1.28 
        # - release-1.27
        kindversion:
        - v0.23.0
        # - 296749aa2de8577f6865e4db1870d2566a28d14b
        - master
    outputs:
      trackingID: ${{ steps.print.outputs.trackingID }}
    env:
      FOCUS: ${{ matrix.focus }}
      PARALLEL: ${{ matrix.parallel }}
      KUBE_TIMEOUT: "-timeout=3h0m"
    #   # PARALLEL: true 
    #   SKIP: \[sig-storage\]\[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|NFS|nfs|inline.execution.and.attach|should.be.rejected.when.no.endpoints.exist
    steps:
      - name: print 
        id: print
        run: |
          env
          echo "trackingID=$RUNNER_TRACKING_ID" >> "$GITHUB_OUTPUT"
      # - uses: oras-project/setup-oras@v1
      #   with:
      #     version: 1.0.0
      # - name: checkoutactions
      #   uses: actions/checkout@v4
      #   with:
      #     repository: kubernetes/kubernetes
      #     fetch-depth: 0
      #     ref: ${{ matrix.branch }}
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: checkout kubernetes
        run: |
          git clone https://github.com/kubernetes/kubernetes
          cd kubernetes

          prefix="release-"
          if [[ ${{ matrix.branch }} =~ ^$prefix ]]; then
            if [[ ${{ matrix.branch }} != "master" ]];then
              git reset --hard ${{ matrix.branch }}
            fi
          else 
            git checkout ${{ matrix.branch }}
          fi
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/kubernetes/go.mod
      - name: get kind
        run: |
          cd ..
          git clone https://github.com/kubernetes-sigs/kind 
          cd kind 
          prefix="v"
          if [[ ${{ matrix.kindversion }} =~ ^$prefix ]]; then
            git reset --hard ${{ matrix.kindversion }}
          else 
            if [[ ${{ matrix.kindversion }} != "master" ]];then
              git checkout ${{ matrix.kindversion }}
            fi
          fi

          # git reset --hard 58e30d99be0a826111a415cb2b44062a78d04817
          make 
          mv bin/kind /usr/local/bin/kind
          chmod +x /usr/local/bin/kind
          #hack/ci/e2e-k8s.sh
          mv hack/ci/e2e-k8s.sh /usr/local/bin/
          kind version

      - name: update
        run: |
          apt-get update
          apt-get install -y netbase nfs-common=1:1.2.8-9ubuntu12

      - name: run
        run: |

          cd kubernetes

          #git reset --hard 77dfd63d1dbe24bd96e579a6bea5c4fb3732d81d
          # 9228b09c3f57e2302c423acb2b9f59c031acf764 Bump containerd to 1.7.15
          #TODO kind commit 296749aa2de8577f6865e4db1870d2566a28d14b  support kube-proxy nftables mode 试试这个

          # git clone https://github.com/kubernetes-sigs/kind 
          # cd kind 
          # git reset --hard 58e30d99be0a826111a415cb2b44062a78d04817
          # make 
          # mv bin/kind /usr/local/bin/kind
          # chmod +x /usr/local/bin/kind
          # #hack/ci/e2e-k8s.sh
          # mv hack/ci/e2e-k8s.sh /usr/local/bin/
          # cd ../lanactions

          #export FOCUS="."
          #export FOCUS="should store data"
          #export PARALLEL=true
          #export SKIP="\[sig-storage\]|\[sig-storage, Slow\]|\[sig-storage\]\[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|NFS|nfs|inline.execution.and.attach|should.be.rejected.when.no.endpoints.exist"
          export SKIP="\[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|NFS|nfs|inline.execution.and.attach|should.be.rejected.when.no.endpoints.exist"

          #curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/"
          #wget https://github.com/kubernetes-sigs/kind/releases/download/v0.23.0/kind-linux-amd64
          #chmod +x kind-linux-amd64
          #mv kind-linux-amd64 /usr/local/bin/kind 
          
          e2e-k8s.sh
          #curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      - name: check artifacts
        if: always()
        run: |
          docker ps -a 
          ls kubernetes/_artifacts
          # docker inspect kind-control-plane

      # - name: Get job info
      #   id: my_action
      #   uses: daleyjem/gh-job-id@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     job_name: "pull-kubernetes-e2e-kind"

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        if: always()
        with:
          name: kind_e2e_parallel_${{ matrix.parallel }}_${{ matrix.branch }}_${{ matrix.kindversion }}_${{ github.run_id }}_${{ steps.print.outputs.trackingID }}
          path: kubernetes/_artifacts
